/**
 * 延迟加载的Minecraft枚举库
 * 所有枚举数据在首次访问时加载，优化启动性能
 */

const lazyData = {
  BlockNameMap: null as any | null,
  EntityNameList: null as any | null,
  ItemNameMap: null as any | null,
  MinecraftStats: null as any | null,
  MinecraftStatsDetail: null as any | null,
  ParticleNames: null as any | null,
};



export const BlockNameMap = {
  get all(): Record<string, string> {
    if (!lazyData.BlockNameMap) {
      lazyData.BlockNameMap = {
        "air": "空气",
        "stone": "石头",
        "granite": "花岗岩",
        "polished_granite": "磨制花岗岩",
        "diorite": "闪长岩",
        "polished_diorite": "磨制闪长岩",
        "andesite": "安山岩",
        "polished_andesite": "磨制安山岩",
        "grass": "草方块",
        "dirt": "泥土",
        "coarse_dirt": "砂土",
        "podzol": "灰化土",
        "cobblestone": "圆石",
        "oak_planks": "橡木木板",
        "spruce_planks": "云杉木板",
        "birch_planks": "白桦木板",
        "jungle_planks": "丛林木板",
        "acacia_planks": "金合欢木板",
        "dark_oak_planks": "深色橡木木板",
        "oak_sapling": "橡树树苗",
        "spruce_sapling": "云杉树苗",
        "birch_sapling": "白桦树苗",
        "jungle_sapling": "丛林树苗",
        "acacia_sapling": "金合欢树苗",
        "dark_oak_sapling": "深色橡木树苗",
        "bedrock": "基岩",
        "flowing_water": "流动的水",
        "water": "水",
        "flowing_lava": "流动的岩浆",
        "lava": "岩浆",
        "sand": "沙子",
        "red_sand": "红沙",
        "gravel": "砂砾",
        "gold_ore": "金矿石",
        "iron_ore": "铁矿石",
        "coal_ore": "煤矿石",
        "oak_log": "橡木",
        "spruce_log": "云杉木",
        "birch_log": "白桦木",
        "jungle_log": "丛林木",
        "acacia_log": "金合欢木",
        "dark_oak_log": "深色橡木",
        "oak_leaves": "橡树树叶",
        "spruce_leaves": "云杉树叶",
        "birch_leaves": "白桦树叶",
        "jungle_leaves": "丛林树叶",
        "acacia_leaves": "金合欢树叶",
        "dark_oak_leaves": "深色橡木树叶",
        "sponge": "海绵",
        "wet_sponge": "湿海绵",
        "glass": "玻璃",
        "lapis_ore": "青金石矿石",
        "lapis_block": "青金石块",
        "dispenser": "发射器",
        "sandstone": "沙石",
        "chiseled_sandstone": "錾制沙石",
        "cut_sandstone": "切制沙石",
        "noteblock": "音符盒",
        "bed": "床",
        "golden_rail": "充能铁轨",
        "detector_rail": "探测铁轨",
        "sticky_piston": "粘性活塞",
        "web": "蜘蛛网",
        "tallgrass": "草丛",
        "deadbush": "枯死的灌木",
        "piston": "活塞",
        "piston_head": "活塞头",
        "wool": "羊毛",
        "piston_extension": "移动的活塞",
        "yellow_flower": "蒲公英",
        "poppy": "罂粟",
        "blue_orchid": "兰花",
        "allium": "绒球葱",
        "azure_bluet": "蓝花美耳草",
        "red_tulip": "红色郁金香",
        "orange_tulip": "橙色郁金香",
        "white_tulip": "白色郁金香",
        "pink_tulip": "粉红色郁金香",
        "oxeye_daisy": "滨菊",
        "brown_mushroom": "棕色蘑菇",
        "red_mushroom": "红色蘑菇",
        "gold_block": "金块",
        "iron_block": "铁块",
        "double_stone_slab": "双石台阶",
        "stone_slab": "石台阶",
        "brick_block": "砖块",
        "tnt": "TNT",
        "bookshelf": "书架",
        "mossy_cobblestone": "苔石",
        "obsidian": "黑曜石",
        "torch": "火把",
        "fire": "火",
        "mob_spawner": "刷怪笼",
        "oak_stairs": "橡木楼梯",
        "chest": "箱子",
        "redstone_wire": "红石线",
        "diamond_ore": "钻石矿石",
        "diamond_block": "钻石块",
        "crafting_table": "工作台",
        "wheat": "小麦作物",
        "farmland": "耕地",
        "furnace": "熔炉",
        "lit_furnace": "燃烧的熔炉",
        "standing_sign": "告示牌",
        "wooden_door": "橡木门",
        "ladder": "梯子",
        "rail": "铁轨",
        "stone_stairs": "石楼梯",
        "wall_sign": "墙上的告示牌",
        "lever": "拉杆",
        "stone_pressure_plate": "石质压力板",
        "iron_door": "铁门",
        "wooden_pressure_plate": "木质压力板",
        "redstone_ore": "红石矿石",
        "lit_redstone_ore": "发光的红石矿石",
        "unlit_redstone_torch": "红石火把",
        "redstone_torch": "红石火把",
        "stone_button": "石质按钮",
        "snow_layer": "雪层",
        "ice": "冰",
        "snow": "雪块",
        "cactus": "仙人掌",
        "clay": "粘土",
        "reeds": "甘蔗",
        "jukebox": "唱片机",
        "fence": "橡木栅栏",
        "pumpkin": "南瓜",
        "netherrack": "地狱岩",
        "soul_sand": "灵魂沙",
        "glowstone": "荧石",
        "portal": "下界传送门",
        "lit_pumpkin": "南瓜灯",
        "cake": "蛋糕",
        "unpowered_repeater": "红石中继器",
        "powered_repeater": "红石中继器",
        "stained_glass": "染色玻璃",
        "trapdoor": "活板门",
        "monster_egg": "怪物蛋",
        "stonebrick": "石砖",
        "brown_mushroom_block": "棕色蘑菇方块",
        "red_mushroom_block": "红色蘑菇方块",
        "iron_bars": "铁栏杆",
        "glass_pane": "玻璃板",
        "melon_block": "西瓜",
        "pumpkin_stem": "南瓜茎",
        "melon_stem": "西瓜茎",
        "vine": "藤蔓",
        "fence_gate": "橡木栅栏门",
        "brick_stairs": "砖楼梯",
        "stone_brick_stairs": "石砖楼梯",
        "mycelium": "菌丝",
        "waterlily": "睡莲",
        "nether_brick": "下界砖块",
        "nether_brick_fence": "下界砖栅栏",
        "nether_brick_stairs": "下界砖楼梯",
        "nether_wart": "下界疣",
        "enchanting_table": "附魔台",
        "brewing_stand": "酿造台",
        "cauldron": "炼药锅",
        "end_portal": "末地传送门",
        "end_portal_frame": "末地传送门框架",
        "end_stone": "末地石",
        "dragon_egg": "龙蛋",
        "redstone_lamp": "红石灯",
        "lit_redstone_lamp": "红石灯",
        "double_wooden_slab": "双木台阶",
        "wooden_slab": "木台阶",
        "cocoa": "可可果",
        "sandstone_stairs": "沙石楼梯",
        "emerald_ore": "绿宝石矿石",
        "ender_chest": "末影箱",
        "tripwire_hook": "绊线钩",
        "tripwire": "绊线",
        "emerald_block": "绿宝石块",
        "spruce_stairs": "云杉木楼梯",
        "birch_stairs": "白桦木楼梯",
        "jungle_stairs": "丛林木楼梯",
        "command_block": "命令方块",
        "beacon": "信标",
        "cobblestone_wall": "圆石墙",
        "flower_pot": "花盆",
        "carrots": "胡萝卜作物",
        "potatoes": "马铃薯作物",
        "wooden_button": "木质按钮",
        "skull": "生物头颅",
        "anvil": "铁砧",
        "trapped_chest": "陷阱箱",
        "light_weighted_pressure_plate": "轻质测重压力板",
        "heavy_weighted_pressure_plate": "重质测重压力板",
        "unpowered_comparator": "红石比较器",
        "powered_comparator": "红石比较器",
        "daylight_detector": "阳光传感器",
        "redstone_block": "红石块",
        "quartz_ore": "下界石英矿石",
        "hopper": "漏斗",
        "quartz_block": "石英块",
        "quartz_stairs": "石英楼梯",
        "activator_rail": "激活铁轨",
        "dropper": "投掷器",
        "stained_hardened_clay": "染色陶瓦",
        "stained_glass_pane": "染色玻璃板",
        "leaves2": "金合欢树叶",
        "log2": "金合欢木",
        "acacia_stairs": "金合欢木楼梯",
        "dark_oak_stairs": "深色橡木楼梯",
        "slime": "粘液块",
        "barrier": "屏障",
        "iron_trapdoor": "铁活板门",
        "prismarine": "海晶石",
        "sea_lantern": "海晶灯",
        "hay_block": "干草块",
        "carpet": "地毯",
        "hardened_clay": "陶瓦",
        "coal_block": "煤炭块",
        "packed_ice": "浮冰",
        "double_plant": "大型植物",
        "standing_banner": "旗帜",
        "wall_banner": "墙上的旗帜",
        "daylight_detector_inverted": "反向阳光传感器",
        "red_sandstone": "红沙石",
        "chiseled_red_sandstone": "錾制红沙石",
        "cut_red_sandstone": "切制红沙石",
        "red_sandstone_stairs": "红沙石楼梯",
        "double_stone_slab2": "双红沙石台阶",
        "stone_slab2": "红沙石台阶",
        "spruce_fence_gate": "云杉木栅栏门",
        "birch_fence_gate": "白桦木栅栏门",
        "jungle_fence_gate": "丛林木栅栏门",
        "dark_oak_fence_gate": "深色橡木栅栏门",
        "acacia_fence_gate": "金合欢木栅栏门",
        "spruce_fence": "云杉木栅栏",
        "birch_fence": "白桦木栅栏",
        "jungle_fence": "丛林木栅栏",
        "dark_oak_fence": "深色橡木栅栏",
        "acacia_fence": "金合欢木栅栏",
        "spruce_door": "云杉木门",
        "birch_door": "白桦木门",
        "jungle_door": "丛林木门",
        "acacia_door": "金合欢木门",
        "dark_oak_door": "深色橡木门",
        "end_rod": "末地烛",
        "chorus_plant": "紫颂植物",
        "chorus_flower": "紫颂花",
        "purpur_block": "紫珀块",
        "purpur_pillar": "紫珀柱",
        "purpur_stairs": "紫珀楼梯",
        "purpur_double_slab": "双紫珀台阶",
        "purpur_slab": "紫珀台阶",
        "end_bricks": "末地石砖",
        "beetroots": "甜菜根作物",
        "grass_path": "草径",
        "end_gateway": "末地折跃门",
        "repeating_command_block": "循环型命令方块",
        "chain_command_block": "连锁型命令方块",
        "frosted_ice": "霜冰",
        "magma": "岩浆块",
        "nether_wart_block": "下界疣块",
        "red_nether_brick": "红色下界砖块",
        "bone_block": "骨块",
        "structure_void": "结构空位",
        "observer": "侦测器",
        "white_shulker_box": "白色潜影盒",
        "orange_shulker_box": "橙色潜影盒",
        "magenta_shulker_box": "品红色潜影盒",
        "light_blue_shulker_box": "淡蓝色潜影盒",
        "yellow_shulker_box": "黄色潜影盒",
        "lime_shulker_box": "黄绿色潜影盒",
        "pink_shulker_box": "粉红色潜影盒",
        "gray_shulker_box": "灰色潜影盒",
        "silver_shulker_box": "淡灰色潜影盒",
        "cyan_shulker_box": "青色潜影盒",
        "purple_shulker_box": "紫色潜影盒",
        "blue_shulker_box": "蓝色潜影盒",
        "brown_shulker_box": "棕色潜影盒",
        "green_shulker_box": "绿色潜影盒",
        "red_shulker_box": "红色潜影盒",
        "black_shulker_box": "黑色潜影盒",
        "white_glazed_terracotta": "白色带釉陶瓦",
        "orange_glazed_terracotta": "橙色带釉陶瓦",
        "magenta_glazed_terracotta": "品红色带釉陶瓦",
        "light_blue_glazed_terracotta": "淡蓝色带釉陶瓦",
        "yellow_glazed_terracotta": "黄色带釉陶瓦",
        "lime_glazed_terracotta": "黄绿色带釉陶瓦",
        "pink_glazed_terracotta": "粉红色带釉陶瓦",
        "gray_glazed_terracotta": "灰色带釉陶瓦",
        "silver_glazed_terracotta": "淡灰色带釉陶瓦",
        "cyan_glazed_terracotta": "青色带釉陶瓦",
        "purple_glazed_terracotta": "紫色带釉陶瓦",
        "blue_glazed_terracotta": "蓝色带釉陶瓦",
        "brown_glazed_terracotta": "棕色带釉陶瓦",
        "green_glazed_terracotta": "绿色带釉陶瓦",
        "red_glazed_terracotta": "红色带釉陶瓦",
        "black_glazed_terracotta": "黑色带釉陶瓦",
        "concrete": "混凝土",
        "concrete_powder": "混凝土粉末",
        "structure_block": "结构方块"
      };
    }
    return { ...lazyData.BlockNameMap }; // 返回副本避免外部修改
  },

  // 获取所有键名
  get keys(): string[] {
    return Object.keys(this.all);
  },

  // 按前缀过滤键名
  filterByPrefix(prefix: string): string[] {
    const lowerPrefix = prefix.toLowerCase();
    return this.keys.filter(key =>
      key.toLowerCase().startsWith(lowerPrefix)
    );
  },

  // 获取键对应的描述
  getDescription(key: string): string {
    return this.all[key] || key;
  }
};

export const EntityNameList = {
  get all(): Array<{ name: string; desc: string }> {
    if (!lazyData.EntityNameList) {
      lazyData.EntityNameList = [
        { name: 'area_effect_cloud', desc: '区域效果云' },
        { name: 'armor_stand', desc: '盔甲架' },
        { name: 'arrow', desc: '箭' },
        { name: 'bat', desc: '蝙蝠' },
        { name: 'blaze', desc: '烈焰人' },
        { name: 'boat', desc: '船' },
        { name: 'cave_spider', desc: '洞穴蜘蛛' },
        { name: 'chest_minecart', desc: '箱子矿车' },
        { name: 'chicken', desc: '鸡' },
        { name: 'commandblock_minecart', desc: '命令方块矿车' },
        { name: 'cow', desc: '牛' },
        { name: 'creeper', desc: '苦力怕' },
        { name: 'donkey', desc: '驴' },
        { name: 'dragon_fireball', desc: '龙火球' },
        { name: 'egg', desc: '鸡蛋' },
        { name: 'elder_guardian', desc: '远古守卫者' },
        { name: 'ender_crystal', desc: '末影水晶' },
        { name: 'ender_dragon', desc: '末影龙' },
        { name: 'ender_pearl', desc: '末影珍珠' },
        { name: 'enderman', desc: '末影人' },
        { name: 'endermite', desc: '末影螨' },
        { name: 'evocation_fangs', desc: '唤魔者的尖牙' },
        { name: 'evocation_illager', desc: '唤魔者' },
        { name: 'eye_of_ender_signal', desc: '末影之眼信号' },
        { name: 'falling_block', desc: '下落的方块' },
        { name: 'fireball', desc: '火球' },
        { name: 'fireworks_rocket', desc: '烟花火箭' },
        { name: 'furnace_minecart', desc: '熔炉矿车' },
        { name: 'ghast', desc: '恶魂' },
        { name: 'giant', desc: '巨人' },
        { name: 'guardian', desc: '守卫者' },
        { name: 'hopper_minecart', desc: '漏斗矿车' },
        { name: 'horse', desc: '马' },
        { name: 'husk', desc: '尸壳' },
        { name: 'illusion_illager', desc: '幻术师' },
        { name: 'item', desc: '物品实体' },
        { name: 'item_frame', desc: '物品展示框' },
        { name: 'leash_knot', desc: '拴绳结' },
        { name: 'lightning_bolt', desc: '闪电' },
        { name: 'llama', desc: ' llama' },
        { name: 'llama_spit', desc: ' llama spit' },
        { name: 'magma_cube', desc: '岩浆怪' },
        { name: 'minecart', desc: '矿车' },
        { name: 'mooshroom', desc: '蘑菇牛（哞菇）' },
        { name: 'mule', desc: '骡' },
        { name: 'ocelot', desc: '豹猫' },
        { name: 'painting', desc: '画' },
        { name: 'parrot', desc: '鹦鹉' },
        { name: 'pig', desc: '猪' },
        { name: 'polar_bear', desc: '北极熊' },
        { name: 'potion', desc: '药水' },
        { name: 'rabbit', desc: '兔子' },
        { name: 'sheep', desc: '羊' },
        { name: 'shulker', desc: '潜影贝' },
        { name: 'shulker_bullet', desc: '潜影贝子弹' },
        { name: 'silverfish', desc: '蠹虫' },
        { name: 'skeleton', desc: '骷髅' },
        { name: 'skeleton_horse', desc: '骷髅马' },
        { name: 'slime', desc: '史莱姆' },
        { name: 'small_fireball', desc: '小火球' },
        { name: 'snowball', desc: '雪球' },
        { name: 'snowman', desc: '雪傀儡' },
        { name: 'spawner_minecart', desc: '刷怪笼矿车' },
        { name: 'spectral_arrow', desc: ' spectral arrow' },
        { name: 'spider', desc: '蜘蛛' },
        { name: 'squid', desc: '鱿鱼' },
        { name: 'stray', desc: '流浪者' },
        { name: 'tnt', desc: 'TNT' },
        { name: 'tnt_minecart', desc: 'TNT矿车' },
        { name: 'vex', desc: '恼鬼' },
        { name: 'villager', desc: '村民' },
        { name: 'villager_golem', desc: '铁傀儡' },
        { name: 'vindication_illager', desc: '卫道士' },
        { name: 'witch', desc: '女巫' },
        { name: 'wither', desc: '凋零' },
        { name: 'wither_skeleton', desc: '凋零骷髅' },
        { name: 'wither_skull', desc: '凋零头颅' },
        { name: 'wolf', desc: '狼' },
        { name: 'xp_bottle', desc: '经验瓶' },
        { name: 'xp_orb', desc: '经验球' },
        { name: 'zombie', desc: '僵尸' },
        { name: 'zombie_horse', desc: '僵尸马' },
        { name: 'zombie_pigman', desc: '僵尸猪人' },
        { name: 'zombie_villager', desc: '僵尸村民' }
      ];
    }
    return [...lazyData.EntityNameList]; // 返回副本避免外部修改
  },

  // 按前缀过滤枚举项
  filterByPrefix(prefix: string): Array<{ name: string; desc: string }> {
    const lowerPrefix = prefix.toLowerCase();
    return this.all.filter(item =>
      item.name.toLowerCase().startsWith(lowerPrefix)
    );
  }
};
export const ItemNameMap = {
  get all(): Record<string, string> {
    if (!lazyData.ItemNameMap) {
      lazyData.ItemNameMap = {
        "acacia_boat": "金合欢木船",
        "acacia_door": "金合欢木门",
        "acacia_fence": "金合欢木栅栏",
        "acacia_fence_gate": "金合欢木栅栏门",
        "acacia_stairs": "金合欢木楼梯",
        "activator_rail": "激活铁轨",
        "air": "空气",
        "anvil": "铁砧",
        "apple": "苹果",
        "armor_stand": "盔甲架",
        "arrow": "箭",
        "baked_potato": "烤马铃薯",
        "banner": "旗帜",
        "barrier": "屏障",
        "beacon": "信标",
        "bed": "床",
        "bedrock": "基岩",
        "beef": "生牛肉",
        "beetroot": "甜菜根",
        "beetroot_seeds": "甜菜种子",
        "beetroot_soup": "甜菜汤",
        "birch_boat": "白桦木船",
        "birch_door": "白桦木门",
        "birch_fence": "白桦木栅栏",
        "birch_fence_gate": "白桦木栅栏门",
        "birch_stairs": "白桦木楼梯",
        "black_glazed_terracotta": "黑色带釉陶瓦",
        "black_shulker_box": "黑色潜影盒",
        "blaze_powder": "烈焰粉",
        "blaze_rod": "烈焰棒",
        "blue_glazed_terracotta": "蓝色带釉陶瓦",
        "blue_shulker_box": "蓝色潜影盒",
        "boat": "船",
        "bone": "骨头",
        "bone_block": "骨块",
        "book": "书",
        "bookshelf": "书架",
        "bow": "弓",
        "bowl": "碗",
        "bread": "面包",
        "brewing_stand": "酿造台",
        "brick": "红砖",
        "brick_block": "红砖块",
        "brick_stairs": "红砖楼梯",
        "brown_glazed_terracotta": "棕色带釉陶瓦",
        "brown_mushroom": "棕色蘑菇",
        "brown_mushroom_block": "棕色蘑菇块",
        "brown_shulker_box": "棕色潜影盒",
        "bucket": "桶",
        "cactus": "仙人掌",
        "cake": "蛋糕",
        "carpet": "地毯",
        "carrot": "胡萝卜",
        "carrot_on_a_stick": "胡萝卜钓竿",
        "cauldron": "炼药锅",
        "chain_command_block": "连锁型命令方块",
        "chainmail_boots": "锁链靴子",
        "chainmail_chestplate": "锁链胸甲",
        "chainmail_helmet": "锁链头盔",
        "chainmail_leggings": "锁链护腿",
        "chest": "箱子",
        "chest_minecart": "运输矿车",
        "chicken": "生鸡肉",
        "chorus_flower": "紫颂花",
        "chorus_fruit": "紫颂果",
        "chorus_fruit_popped": "爆裂紫颂果",
        "chorus_plant": "紫颂植物",
        "clay": "粘土",
        "clay_ball": "粘土球",
        "clock": "时钟",
        "coal": "煤炭",
        "coal_block": "煤炭块",
        "coal_ore": "煤矿石",
        "cobblestone": "圆石",
        "cobblestone_wall": "圆石墙",
        "command_block": "命令方块",
        "command_block_minecart": "命令方块矿车",
        "comparator": "红石比较器",
        "compass": "指南针",
        "concrete": "混凝土",
        "concrete_powder": "混凝土粉末",
        "cooked_beef": "牛排",
        "cooked_chicken": "熟鸡肉",
        "cooked_fish": "熟鱼",
        "cooked_mutton": "熟羊肉",
        "cooked_porkchop": "熟猪排",
        "cooked_rabbit": "熟兔肉",
        "cookie": "曲奇",
        "crafting_table": "工作台",
        "cyan_glazed_terracotta": "青色带釉陶瓦",
        "cyan_shulker_box": "青色潜影盒",
        "dark_oak_boat": "深色橡木船",
        "dark_oak_door": "深色橡木门",
        "dark_oak_fence": "深色橡木栅栏",
        "dark_oak_fence_gate": "深色橡木栅栏门",
        "dark_oak_stairs": "深色橡木楼梯",
        "daylight_detector": "阳光探测器",
        "deadbush": "枯灌木",
        "detector_rail": "探测铁轨",
        "diamond": "钻石",
        "diamond_axe": "钻石斧",
        "diamond_block": "钻石块",
        "diamond_boots": "钻石靴子",
        "diamond_chestplate": "钻石胸甲",
        "diamond_helmet": "钻石头盔",
        "diamond_hoe": "钻石锄",
        "diamond_horse_armor": "钻石马铠",
        "diamond_leggings": "钻石护腿",
        "diamond_ore": "钻石矿石",
        "diamond_pickaxe": "钻石镐",
        "diamond_shovel": "钻石锹",
        "diamond_sword": "钻石剑",
        "dirt": "泥土",
        "dispenser": "发射器",
        "double_plant": "双层植物",
        "dragon_breath": "龙息",
        "dragon_egg": "龙蛋",
        "dropper": "投掷器",
        "dye": "染料",
        "egg": "鸡蛋",
        "elytra": "鞘翅",
        "emerald": "绿宝石",
        "emerald_block": "绿宝石块",
        "emerald_ore": "绿宝石矿石",
        "enchanted_book": "附魔书",
        "enchanting_table": "附魔台",
        "end_bricks": "末地石砖",
        "end_crystal": "末地水晶",
        "end_portal_frame": "末地传送门框架",
        "end_rod": "末地烛",
        "end_stone": "末地石",
        "ender_chest": "末影箱",
        "ender_eye": "末影之眼",
        "ender_pearl": "末影珍珠",
        "experience_bottle": "经验瓶",
        "farmland": "耕地",
        "feather": "羽毛",
        "fence": "栅栏",
        "fence_gate": "栅栏门",
        "fermented_spider_eye": "发酵蛛眼",
        "filled_map": "地图",
        "fire_charge": "火焰弹",
        "firework_charge": "烟火之星",
        "fireworks": "烟花火箭",
        "fish": "鱼",
        "fishing_rod": "钓鱼竿",
        "flint": "燧石",
        "flint_and_steel": "打火石",
        "flower_pot": "花盆",
        "furnace": "熔炉",
        "furnace_minecart": "动力矿车",
        "ghast_tear": "恶魂之泪",
        "glass": "玻璃",
        "glass_bottle": "玻璃瓶",
        "glass_pane": "玻璃板",
        "glowstone": "荧石",
        "glowstone_dust": "荧石粉",
        "gold_block": "金块",
        "gold_ingot": "金锭",
        "gold_nugget": "金粒",
        "gold_ore": "金矿石",
        "golden_apple": "金苹果",
        "golden_axe": "金斧",
        "golden_boots": "金靴子",
        "golden_carrot": "金胡萝卜",
        "golden_chestplate": "金胸甲",
        "golden_helmet": "金头盔",
        "golden_hoe": "金锄",
        "golden_horse_armor": "金马铠",
        "golden_leggings": "金护腿",
        "golden_pickaxe": "金镐",
        "golden_rail": "充能铁轨",
        "golden_shovel": "金锹",
        "golden_sword": "金剑",
        "grass": "草",
        "grass_path": "草径",
        "gravel": "沙砾",
        "gray_glazed_terracotta": "灰色带釉陶瓦",
        "gray_shulker_box": "灰色潜影盒",
        "green_glazed_terracotta": "绿色带釉陶瓦",
        "green_shulker_box": "绿色潜影盒",
        "gunpowder": "火药",
        "hardened_clay": "硬化粘土",
        "hay_block": "干草块",
        "heavy_weighted_pressure_plate": "重质测重压力板",
        "hopper": "漏斗",
        "hopper_minecart": "漏斗矿车",
        "ice": "冰",
        "iron_axe": "铁斧",
        "iron_bars": "铁栏杆",
        "iron_block": "铁块",
        "iron_boots": "铁靴子",
        "iron_chestplate": "铁胸甲",
        "iron_door": "铁门",
        "iron_helmet": "铁头盔",
        "iron_hoe": "铁锄",
        "iron_horse_armor": "铁马铠",
        "iron_ingot": "铁锭",
        "iron_leggings": "铁护腿",
        "iron_nugget": "铁粒",
        "iron_ore": "铁矿石",
        "iron_pickaxe": "铁镐",
        "iron_shovel": "铁锹",
        "iron_sword": "铁剑",
        "iron_trapdoor": "铁活板门",
        "item_frame": "物品展示框",
        "jukebox": "唱片机",
        "jungle_boat": "丛林木船",
        "jungle_door": "丛林木门",
        "jungle_fence": "丛林木栅栏",
        "jungle_fence_gate": "丛林木栅栏门",
        "jungle_stairs": "丛林木楼梯",
        "knowledge_book": "知识之书",
        "ladder": "梯子",
        "lapis_block": "青金石块",
        "lapis_ore": "青金石矿石",
        "lava_bucket": "熔岩桶",
        "lead": "栓绳",
        "leather": "皮革",
        "leather_boots": "皮革靴子",
        "leather_chestplate": "皮革外套",
        "leather_helmet": "皮革帽子",
        "leather_leggings": "皮革裤子",
        "leaves": "树叶",
        "leaves2": "树叶2",
        "lever": "拉杆",
        "light_blue_glazed_terracotta": "淡蓝色带釉陶瓦",
        "light_blue_shulker_box": "淡蓝色潜影盒",
        "light_weighted_pressure_plate": "轻质测重压力板",
        "lime_glazed_terracotta": "黄绿色带釉陶瓦",
        "lime_shulker_box": "黄绿色潜影盒",
        "lingering_potion": "滞留药水",
        "lit_pumpkin": "南瓜灯",
        "log": "原木",
        "log2": "原木2",
        "magenta_glazed_terracotta": "品红色带釉陶瓦",
        "magenta_shulker_box": "品红色潜影盒",
        "magma": "岩浆块",
        "magma_cream": "岩浆膏",
        "map": "地图",
        "melon": "西瓜片",
        "melon_block": "西瓜",
        "melon_seeds": "西瓜种子",
        "milk_bucket": "奶桶",
        "minecart": "矿车",
        "mob_spawner": "刷怪笼",
        "monster_egg": "蠹虫方块",
        "mossy_cobblestone": "苔石",
        "mushroom_stew": "蘑菇煲",
        "mutton": "生羊肉",
        "mycelium": "菌丝",
        "name_tag": "命名牌",
        "nether_brick": "下界砖",
        "nether_brick_fence": "下界砖栅栏",
        "nether_brick_stairs": "下界砖楼梯",
        "nether_star": "下界之星",
        "nether_wart": "下界疣",
        "nether_wart_block": "下界疣块",
        "netherbrick": "下界砖",
        "netherrack": "下界岩",
        "noteblock": "音符盒",
        "oak_stairs": "橡木楼梯",
        "observer": "侦测器",
        "obsidian": "黑曜石",
        "orange_glazed_terracotta": "橙色带釉陶瓦",
        "orange_shulker_box": "橙色潜影盒",
        "packed_ice": "浮冰",
        "painting": "画",
        "paper": "纸",
        "pink_glazed_terracotta": "粉红色带釉陶瓦",
        "pink_shulker_box": "粉红色潜影盒",
        "piston": "活塞",
        "planks": "木板",
        "poisonous_potato": "毒马铃薯",
        "porkchop": "生猪排",
        "potato": "马铃薯",
        "potion": "药水",
        "prismarine": "海晶石",
        "prismarine_crystals": "海晶砂粒",
        "prismarine_shard": "海晶碎片",
        "pumpkin": "南瓜",
        "pumpkin_pie": "南瓜派",
        "pumpkin_seeds": "南瓜种子",
        "purple_glazed_terracotta": "紫色带釉陶瓦",
        "purple_shulker_box": "紫色潜影盒",
        "purpur_block": "紫珀块",
        "purpur_pillar": "紫珀柱",
        "purpur_slab": "紫珀台阶",
        "purpur_stairs": "紫珀楼梯",
        "quartz": "下界石英",
        "quartz_block": "石英块",
        "quartz_ore": "下界石英矿石",
        "quartz_stairs": "石英楼梯",
        "rabbit": "生兔肉",
        "rabbit_foot": "兔子脚",
        "rabbit_hide": "兔子皮",
        "rabbit_stew": "兔肉煲",
        "rail": "铁轨",
        "record_11": "11号唱片",
        "record_13": "13号唱片",
        "record_blocks": "blocks唱片",
        "record_cat": "cat唱片",
        "record_chirp": "chirp唱片",
        "record_far": "far唱片",
        "record_mall": "mall唱片",
        "record_mellohi": "mellohi唱片",
        "record_stal": "stal唱片",
        "record_strad": "strad唱片",
        "record_wait": "wait唱片",
        "record_ward": "ward唱片",
        "red_flower": "红色花",
        "red_glazed_terracotta": "红色带釉陶瓦",
        "red_mushroom": "红色蘑菇",
        "red_mushroom_block": "红色蘑菇块",
        "red_nether_brick": "红色下界砖",
        "red_sandstone": "红砂岩",
        "red_sandstone_stairs": "红砂岩楼梯",
        "red_shulker_box": "红色潜影盒",
        "redstone": "红石粉",
        "redstone_block": "红石块",
        "redstone_lamp": "红石灯",
        "redstone_ore": "红石矿石",
        "redstone_torch": "红石火把",
        "reeds": "甘蔗",
        "repeater": "红石中继器",
        "repeating_command_block": "循环型命令方块",
        "rotten_flesh": "腐肉",
        "saddle": "鞍",
        "sand": "沙子",
        "sandstone": "砂岩",
        "sandstone_stairs": "砂岩楼梯",
        "sapling": "树苗",
        "sea_lantern": "海晶灯",
        "shears": "剪刀",
        "shield": "盾牌",
        "shulker_shell": "潜影壳",
        "sign": "告示牌",
        "silver_glazed_terracotta": "银色带釉陶瓦",
        "silver_shulker_box": "银色潜影盒",
        "skull": "头颅",
        "slime": "粘液块",
        "slime_ball": "粘液球",
        "snow": "雪块",
        "snow_layer": "雪层",
        "snowball": "雪球",
        "soul_sand": "灵魂沙",
        "spawn_egg": "刷怪蛋",
        "speckled_melon": "闪烁的西瓜",
        "spectral_arrow": "光灵箭",
        "spider_eye": "蜘蛛眼",
        "splash_potion": "喷溅药水",
        "sponge": "海绵",
        "spruce_boat": "云杉木船",
        "spruce_door": "云杉木门",
        "spruce_fence": "云杉木栅栏",
        "spruce_fence_gate": "云杉木栅栏门",
        "spruce_stairs": "云杉木楼梯",
        "stained_glass": "染色玻璃",
        "stained_glass_pane": "染色玻璃板",
        "stained_hardened_clay": "染色硬化粘土",
        "stick": "木棍",
        "sticky_piston": "粘性活塞",
        "stone": "石头",
        "stone_axe": "石斧",
        "stone_brick_stairs": "石砖楼梯",
        "stone_button": "石质按钮",
        "stone_hoe": "石锄",
        "stone_pickaxe": "石镐",
        "stone_pressure_plate": "石质压力板",
        "stone_shovel": "石锹",
        "stone_slab": "石台阶",
        "stone_slab2": "台阶",
        "stone_stairs": "石楼梯",
        "stone_sword": "石剑",
        "stonebrick": "石砖",
        "string": "线",
        "structure_block": "结构方块",
        "structure_void": "结构空位",
        "sugar": "糖",
        "tallgrass": "高草",
        "tipped_arrow": "药箭",
        "tnt": "TNT",
        "tnt_minecart": "TNT矿车",
        "torch": "火把",
        "totem_of_undying": "不死图腾",
        "trapdoor": "活板门",
        "trapped_chest": "陷阱箱",
        "tripwire_hook": "绊线钩",
        "vine": "藤蔓",
        "water_bucket": "水桶",
        "waterlily": "睡莲",
        "web": "蜘蛛网",
        "wheat": "小麦",
        "wheat_seeds": "小麦种子",
        "white_glazed_terracotta": "白色带釉陶瓦",
        "white_shulker_box": "白色潜影盒",
        "wooden_axe": "木斧",
        "wooden_button": "木质按钮",
        "wooden_door": "木门",
        "wooden_hoe": "木锄",
        "wooden_pickaxe": "木镐",
        "wooden_pressure_plate": "木质压力板",
        "wooden_shovel": "木锹",
        "wooden_slab": "木台阶",
        "wooden_sword": "木剑",
        "wool": "羊毛",
        "writable_book": "书与笔",
        "written_book": "成书",
        "yellow_flower": "黄色花",
        "yellow_glazed_terracotta": "黄色带釉陶瓦",
        "yellow_shulker_box": "黄色潜影盒"
      };
    }
    return { ...lazyData.ItemNameMap }; // 返回副本避免外部修改
  },

  // 获取所有键名
  get keys(): string[] {
    return Object.keys(this.all);
  },

  // 按前缀过滤键名
  filterByPrefix(prefix: string): string[] {
    const lowerPrefix = prefix.toLowerCase();
    return this.keys.filter(key =>
      key.toLowerCase().startsWith(lowerPrefix)
    );
  },

  // 获取键对应的描述
  getDescription(key: string): string {
    return this.all[key] || key;
  }
};
export const MinecraftStats = {
  get all(): Array<{ name: string; desc: string }> {
    if (!lazyData.MinecraftStats) {
      lazyData.MinecraftStats = [
        { name: "air", desc: "玩家氧气值" },
        { name: "armor", desc: "玩家护甲值" },
        { name: "dummy", desc: "（只能通过命令改变）" },
        { name: "deathCount", desc: "死亡次数" },
        { name: "food", desc: "食物值" },
        { name: "health", desc: "生命数（正常满血是20）" },
        { name: "killedByTeam.", desc: "被**队击杀次数（**为队伍颜色）" },
        { name: "level", desc: "等级数" },
        { name: "playerKillCount", desc: "玩家击杀数" },
        { name: "stat.", desc: "统计信息（详见具体子项）" },
        { name: "teamkill.", desc: "击杀**队伍的次数（**为队伍颜色）" },
        { name: "totalKillCount", desc: "总击杀数" },
        { name: "trigger", desc: "普通玩家可使用trigger命令设置自己的分数（详见上面目录，可以快速跳转）" },
        { name: "xp", desc: "玩家经验数" }
      ];
    }
    return [...lazyData.MinecraftStats]; // 返回副本避免外部修改
  },

  // 按前缀过滤枚举项
  filterByPrefix(prefix: string): Array<{ name: string; desc: string }> {
    const lowerPrefix = prefix.toLowerCase();
    return this.all.filter(item =>
      item.name.toLowerCase().startsWith(lowerPrefix)
    );
  }
};
export const MinecraftStatsDetail = {
  get all(): Array<{ name: string; desc: string }> {
    if (!lazyData.MinecraftStatsDetail) {
      lazyData.MinecraftStatsDetail = [
        { name: "stat.animalsBred", desc: "动物繁殖次数" },
        { name: "stat.armorCleaned", desc: "在炼药锅中洗掉装备颜色的次数" },
        { name: "stat.aviateOneCm", desc: "滑翔1cm加1分" },
        { name: "stat.bannerCleaned", desc: "在炼药锅洗掉旗帜颜色的次数" },
        { name: "stat.beaconInteraction", desc: "与信标交互次数" },
        { name: "stat.boatOneCm", desc: "划船每1cm加1分" },
        { name: "stat.breakItem.minecraft.", desc: "用坏**工具/装备的次数（**为工具/装备名称）" },
        { name: "stat.brewingstandInteraction", desc: "与酿造台交互的次数" },
        { name: "stat.cakeSlicesEaten", desc: "吃掉的蛋糕片数" },
        { name: "stat.cauldronFilled", desc: "炼药锅装水次数" },
        { name: "stat.cauldronUsed", desc: "炼药锅用水次数" },
        { name: "stat.chestOpened", desc: "打开箱子次数" },
        { name: "stat.climbOneCm", desc: "攀爬1cm（攀爬藤蔓或者梯子）" },
        { name: "stat.craftItem.minecraft.", desc: "合成出**物品" },
        { name: "stat.crouchOneCm", desc: "潜行每1cm加1分" },
        { name: "stat.damageDealt", desc: "造成的伤害总和 * 10" },
        { name: "stat.damageTaken", desc: "受到的伤害总和 * 10" },
        { name: "stat.deaths", desc: "死亡次数" },
        { name: "stat.dispenserInspected", desc: "打开发射器GUI的次数" },
        { name: "stat.peOneCm", desc: "水下移动每1cm加1分" },
        { name: "stat.drop.minecraft.", desc: "丢弃|掉落**物品（**为物品名）" },
        { name: "stat.dropperInspected", desc: "打开投掷器GUI的次数" },
        { name: "stat.enderchestOpened", desc: "打开末影箱次数" },
        { name: "stat.entityKilledBy.", desc: "被**生物击杀的次数（**为生物名）" },
        { name: "stat.fallOneCm", desc: "摔落每1cm加1分" },
        { name: "stat.fishCaught", desc: "钓到鱼的次数" },
        { name: "stat.flowerPotted", desc: "在花盆中种花的次数" },
        { name: "stat.flyOneCm", desc: "飞行1cm加一分" },
        { name: "stat.furnaceInteraction", desc: "与熔炉交互的次数" },
        { name: "stat.hopperInspected", desc: "与漏斗交互次数" },
        { name: "stat.horseOneCm", desc: "骑马每1cm加1分" },
        { name: "stat.itemEnchanted", desc: "物品被附魔" },
        { name: "stat.jump", desc: "跳跃次数" },
        { name: "stat.killEntity.", desc: "击杀**生物次数（**为生物名）" },
        { name: "stat.leaveGame", desc: "离开游戏次数" },
        { name: "stat.mineBlock.minecraft.", desc: "采掘**方块次数（**为方块名）" },
        { name: "stat.minecartOneCm", desc: "坐矿车每1cm加1分" },
        { name: "stat.mobKills", desc: "击杀生物次数" },
        { name: "stat.noteblockPlayed", desc: "击打音符盒次数" },
        { name: "stat.noteblockTuned", desc: "给音符盒调音次数" },
        { name: "stat.pickup.minecraft.", desc: "捡起**物品次数（**为物品名）" },
        { name: "stat.pigOneCm", desc: "骑猪每1cm加1分" },
        { name: "stat.playOneMinute", desc: "玩家游玩游戏刻（每秒加20）" },
        { name: "stat.playerKills", desc: "击杀玩家次数" },
        { name: "stat.recordPlayed", desc: "播放CD次数" },
        { name: "stat.shulkerBoxOpened", desc: "打开潜影箱次数" },
        { name: "stat.sleepInBed", desc: "在床上睡觉次数" },
        { name: "stat.sneakTime", desc: "潜行时间" },
        { name: "stat.sprintOneCm", desc: "疾跑每1cm加1分" },
        { name: "stat.swimOneCm", desc: "游泳每1cm加1分" },
        { name: "stat.talkedToVillager", desc: "打开与村民的交易框次数" },
        { name: "stat.timeSinceDeath", desc: "自从上次死亡以来的时间" },
        { name: "stat.tradedWithVillager", desc: "与村民进行交易的次数" },
        { name: "stat.trappedChestTriggered", desc: "陷阱箱被触发的次数" },
        { name: "stat.useItem.minecraft.", desc: "使用**物品的次数（**为方块或物品名）" },
        { name: "stat.walkOneCm", desc: "行走每1cm加1分" },
      ];
    }
    return [...lazyData.MinecraftStatsDetail]; // 返回副本避免外部修改
  },

  // 按前缀过滤枚举项
  filterByPrefix(prefix: string): Array<{ name: string; desc: string }> {
    const lowerPrefix = prefix.toLowerCase();
    return this.all.filter(item =>
      item.name.toLowerCase().startsWith(lowerPrefix)
    );
  }
};
export const ParticleNames = {
  get all(): Array<{ name: string; desc: string }> {
    if (!lazyData.ParticleNames) {
      lazyData.ParticleNames = [
        { name: "angryVillager", desc: "愤怒的村民" },
        { name: "barrier", desc: "屏障" },
        { name: "blockcrack", desc: "方块破裂" },
        { name: "blockdust", desc: "方块粉尘" },
        { name: "bubble", desc: "气泡" },
        { name: "cloud", desc: "云朵" },
        { name: "crit", desc: "暴击" },
        { name: "damageIndicator", desc: "伤害指示器" },
        { name: "depthsuspend", desc: "深海悬浮" },
        { name: "dragonbreath", desc: "龙息" },
        { name: "dripLava", desc: "熔岩滴落" },
        { name: "dripWater", desc: "水滴落" },
        { name: "droplet", desc: "小水滴" },
        { name: "enchantmenttable", desc: "附魔台" },
        { name: "endRod", desc: "末地烛" },
        { name: "explode", desc: "爆炸" },
        { name: "fallingdust", desc: "下落粉尘" },
        { name: "fireworksSpark", desc: "烟花火花" },
        { name: "flame", desc: "火焰" },
        { name: "footstep", desc: "脚步声" },
        { name: "happyVillager", desc: "快乐的村民" },
        { name: "heart", desc: "爱心" },
        { name: "hugeexplosion", desc: "巨大爆炸" },
        { name: "iconcrack", desc: "图标破裂" },
        { name: "instantSpell", desc: "瞬间法术" },
        { name: "largeexplode", desc: "大型爆炸" },
        { name: "largesmoke", desc: "大量烟雾" },
        { name: "lava", desc: "熔岩" },
        { name: "magicCrit", desc: "魔法暴击" },
        { name: "mobSpell", desc: "生物法术" },
        { name: "mobSpellAmbient", desc: "生物环境法术" },
        { name: "mobappearance", desc: "生物出现" },
        { name: "note", desc: "音符" },
        { name: "portal", desc: "传送门" },
        { name: "reddust", desc: "红色粉尘" },
        { name: "slime", desc: "史莱姆" },
        { name: "smoke", desc: "烟雾" },
        { name: "snowballpoof", desc: "雪球噗声" },
        { name: "snowshovel", desc: "雪铲" },
        { name: "spell", desc: "法术" },
        { name: "spit", desc: "吐息" },
        { name: "splash", desc: "飞溅" },
        { name: "suspended", desc: "悬浮" },
        { name: "sweepAttack", desc: "横扫攻击" },
        { name: "take", desc: "获取" },
        { name: "totem", desc: "图腾" },
        { name: "townaura", desc: "村庄光环" },
        { name: "wake", desc: "波纹" },
        { name: "witchMagic", desc: "女巫魔法" }
      ];
    }
    return [...lazyData.ParticleNames]; // 返回副本避免外部修改
  },

  // 按前缀过滤枚举项
  filterByPrefix(prefix: string): Array<{ name: string; desc: string }> {
    const lowerPrefix = prefix.toLowerCase();
    return this.all.filter(item =>
      item.name.toLowerCase().startsWith(lowerPrefix)
    );
  }
};


export function refreshEnumCache() {
  lazyData.EntityNameList = null;
  lazyData.ItemNameMap = null;
  lazyData.MinecraftStats = null;
  lazyData.MinecraftStatsDetail = null;
  lazyData.ParticleNames = null;
}

